---
- name: Build Docker images for 'playwithansible' project
  hosts: localhost
  gather_facts: no

  vars: 
    registry: ghcr.io
    namespace: playwithansible
    pwa_version: 0.2.4
    img_ansible: "{{ registry }}/{{ namespace }}/ansible-{{ version }}:{{ pwa_version }}"
    img_distribution: "{{ registry }}/{{ namespace }}/{{ item.name }}:{{ pwa_version }}"
    img_webide: "{{ registry }}/{{ namespace }}/webide:{{ pwa_version }}" 
    webide:
      ansible_version: "{{ ansible_versions | last }}"
      theia_version: 1.5.0

  tasks:
  
    - include_vars: ansible_versions.yml
    - include_vars: distribution_versions.yml

    - name: "Build Ansible images {{ ansible_versions | join(', ') }}"
      command: "docker build --build-arg ansible_version={{ version }} -t {{ img_ansible }} ansible"
      loop:
        "{{ ansible_versions }}"
      loop_control:
        loop_var: version

    - name: "Build OS images ({{ distribution_versions | length }} images)"
      command: "docker build --build-arg version={{ item.version }} -t {{ img_distribution }} {{ item.distribution }}"
      loop:
        "{{ distribution_versions }}"

    - name: "Build Web IDE image ({{ img_webide }})"
      command: "docker build --build-arg ansible_version={{ webide.ansible_version }} --build-arg theia_version={{ webide.theia_version }} -t {{ img_webide }} webide"
