version: '3'
services:

  centos7:
    build:
      context: centos
      args:
        version: "7"
    image: ${REGISTRY}/playwithansible/centos7:${PWA_VERSION}
    ports:
      - "22"

  centos8:
    build:
      context: centos
      args:
        version: "8"
    image: ${REGISTRY}/playwithansible/centos8:${PWA_VERSION}
    ports:
      - "22"

  debian8:
    build:
      context: debian
      args:
        version: "8"
    image: ${REGISTRY}/playwithansible/debian8:${PWA_VERSION}
    ports:
      - "22"

  debian9:
    build:
      context: debian
      args:
        version: "9"
    image: ${REGISTRY}/playwithansible/debian9:${PWA_VERSION}
    ports:
      - "22"

  debian10:
    build:
      context: debian
      args:
        version: "10"
    image: ${REGISTRY}/playwithansible/debian10:${PWA_VERSION}
    ports:
      - "22"
  
  fedora30:
    build:
      context: fedora
      args:
        version: "30"
    image: ${REGISTRY}/playwithansible/fedora30:${PWA_VERSION}
    ports:
      - "22"

  fedora31:
    build:
      context: fedora
      args:
        version: "31"
    image: ${REGISTRY}/playwithansible/fedora31:${PWA_VERSION}
    ports:
      - "22"

  fedora32:
    build:
      context: fedora
      args:
        version: "32"
    image: ${REGISTRY}/playwithansible/fedora32:${PWA_VERSION}
    ports:
      - "22"

  ubuntu1804:
    build:
      context: ubuntu
      args:
        version: "18.04"
    image: ${REGISTRY}/playwithansible/ubuntu1804:${PWA_VERSION}
    ports:
      - "22"

  ubuntu1910:
    build:
      context: ubuntu
      args:
        version: "19.10"
    image: ${REGISTRY}/playwithansible/ubuntu1910:${PWA_VERSION}
    ports:
      - "22"

  ubuntu2004:
    build:
      context: ubuntu
      args:
        version: "20.04"
    image: ${REGISTRY}/playwithansible/ubuntu2004:${PWA_VERSION}
    ports:
        - "22"