version: '3'
services:

  centos7:
    build:
      context: centos
      args:
        version: "7"
    image: ${REGISTRY}/${NAMESPACE}/centos7:${PWA_VERSION}
    ports:
      - "22"

  centos8:
    build:
      context: centos
      args:
        version: "8"
    image: ${REGISTRY}/${NAMESPACE}/centos8:${PWA_VERSION}
    ports:
      - "22"

  debian8:
    build:
      context: debian
      args:
        version: "8"
    image: ${REGISTRY}/${NAMESPACE}/debian8:${PWA_VERSION}
    ports:
      - "22"

  debian9:
    build:
      context: debian
      args:
        version: "9"
    image: ${REGISTRY}/${NAMESPACE}/debian9:${PWA_VERSION}
    ports:
      - "22"

  debian10:
    build:
      context: debian
      args:
        version: "10"
    image: ${REGISTRY}/${NAMESPACE}/debian10:${PWA_VERSION}
    ports:
      - "22"
  
  fedora30:
    build:
      context: fedora
      args:
        version: "30"
    image: ${REGISTRY}/${NAMESPACE}/fedora30:${PWA_VERSION}
    ports:
      - "22"

  fedora31:
    build:
      context: fedora
      args:
        version: "31"
    image: ${REGISTRY}/${NAMESPACE}/fedora31:${PWA_VERSION}
    ports:
      - "22"

  fedora32:
    build:
      context: fedora
      args:
        version: "32"
    image: ${REGISTRY}/${NAMESPACE}/fedora32:${PWA_VERSION}
    ports:
      - "22"

  ubuntu1804:
    build:
      context: ubuntu
      args:
        version: "18.04"
    image: ${REGISTRY}/${NAMESPACE}/ubuntu1804:${PWA_VERSION}
    ports:
      - "22"

  ubuntu1910:
    build:
      context: ubuntu
      args:
        version: "19.10"
    image: ${REGISTRY}/${NAMESPACE}/ubuntu1910:${PWA_VERSION}
    ports:
      - "22"

  ubuntu2004:
    build:
      context: ubuntu
      args:
        version: "20.04"
    image: ${REGISTRY}/${NAMESPACE}/ubuntu2004:${PWA_VERSION}
    ports:
        - "22"
  
  webide:
    build:
      context: webide
      args:
        ansible_version: ${ANSIBLE_VERSION}
        theia_version: ${THEIA_VERSION}
    image: ${REGISTRY}/${NAMESPACE}/webide:${PWA_VERSION}
    ports:
      - "3000"